# Generated by Django 3.0.3 on 2020-02-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amino', '0002_auto_20200229_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amino',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='amino',
            name='symbol_3_letters',
        ),
        migrations.AddField(
            model_name='amino',
            name='single_letter_symbol',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amino',
            name='three_letter_symbol',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
