# Generated by Django 3.0.3 on 2020-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
